#!/usr/bin/env python3
"""Build a single-file amalgamation of the zero-dependency core.

Concatenates the internal headers and the non-onnx sources into one
self-contained `.c` you can drop into any project (the sqlite-vec model). The
onnx serving path is left out: it needs onnxruntime, which defeats the point of
a drop-in file. Every reference to it in the core is `#ifdef SQLITE_PREDICT_ONNX`
guarded, so the amalgamation compiles clean without it.

  python scripts/amalgamate.py            # -> dist/sqlite-predict.c
  cc -O3 -fPIC -shared dist/sqlite-predict.c -o predict0.so   # loadable, or
  cc -c -DSQLITE_CORE dist/sqlite-predict.c                   # static into an app

Reproducible: inputs are concatenated in a fixed order; no timestamps.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "dist", "sqlite-predict.c")

# fixed order: public header, sha256 header, internal headers, then sources.
# vendor/sha256 first among sources so its definitions precede any use.
HEADERS = ["sqlite-predict.h", "vendor/sha256.h", "predict-internal.h",
           "predict-student.h"]
SOURCES = ["vendor/sha256.c", "sqlite-predict.c", "predict-forecast.c",
           "predict-registry.c", "predict-tabular.c", "predict-student.c",
           "predict-distill.c"]

# internal includes to drop (their contents are inlined above)
INTERNAL = re.compile(
    r'^\s*#\s*include\s*"(sqlite-predict\.h|sha256\.h|predict-internal\.h|'
    r'predict-student\.h)"\s*$')


def strip_internal_includes(text):
    return "".join(l for l in text.splitlines(keepends=True)
                   if not INTERNAL.match(l))


def read(rel):
    with open(os.path.join(ROOT, rel)) as f:
        return f.read()


with open(os.path.join(ROOT, "VERSION")) as f:
    version = f.read().strip()

parts = [
    "/* sqlite-predict %s -- single-file amalgamation of the zero-dependency\n"
    " * core (forecast / detect_anomalies / predict / distill + the model registry).\n"
    " * Generated by scripts/amalgamate.py; edit the sources, not this file.\n"
    " * The onnx serving path is not included (see the script). */\n"
    % version
]
for h in HEADERS + SOURCES:
    parts.append("\n/* ==== %s ==== */\n" % h)
    parts.append(strip_internal_includes(read(h)))

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    f.write("".join(parts))
print("wrote %s (%d KB)" % (OUT, os.path.getsize(OUT) // 1024))
