"""Export google/timesfm-2.5-200m to an ONNX graph the extension can serve as a
`forecast()` teacher/backend (the `sequence` io_spec layout).

TimesFM 2.5's `forecast()` wraps a `decode` path (which carries a KV-cache) with
revin normalization, flip-invariance (a second decode on the negated input), a
continuous-quantile-head recombination, quantile-crossing repair, and denorm.
Two of those refinements will not survive `torch.export`: a second decode call
introduces data-dependent symints, and the continuous-head step mutates the
output in place. Neither is a property of the *weights*; both are post-processing
around a single decode.

So this script exports only the exportable core (one decode, normalized, no post-
processing) and returns its **raw materials**: the point-head fan and the
quantile-head fan, both normalized. Everything the export refused to trace is
reconstructed outside the graph, at serve time:

  * flip-invariance: call the graph a second time on the reflected context
    (2*mean - context, which normalizes to -x internally) and average the flipped
    fans back in, exactly as `compiled_decode` does, at 2x inference cost.
  * continuous head: recombine the two fans elementwise.
  * quantile-crossing repair + denorm: elementwise.

This recovers the *full* TimesFM, not a single-decode approximation. The C serving
path (predict-onnx.c `sequence` layout) does the same arithmetic this script's
`reconstruct()` proves against the reference pipeline, driven entirely by io_spec
flags (flip_invariance, continuous_head, quantile_crossing_repair, denormalize,
fixed_context) so nothing is keyed on the model's name.

Two hard constraints, both from TimesFM's architecture:
  - CONTEXT IS FIXED AT 512 (max_context). TimesFM patches the context and its
    running-stats loop unrolls only at a fixed patch count, so the graph can't
    take a dynamic length. The io_spec uses patch=512: the serving side truncates
    each series to its last 512 values, and a series shorter than 512 cannot be
    served by this model (use a native distilled student there).
  - HORIZON IS FIXED AT 64 (max_horizon), sliced by the caller.

Tensor contract (what predict-onnx.c's `sequence` io_spec targets):
  input   context     float32 [1, 512]    raw series values (exactly 512)
  output  point_fan   float32 [1, 64, 10] normalized point-head: col 0 mean, 1..9 deciles
  output  quant_fan   float32 [1, 64, 10] normalized quantile-head, same column layout

Register it (the flags below tell the extension to rebuild the full model):

  SELECT predict_register('timesfm', json_object(
    'runtime','onnx','kind','ts-fm','license','Apache-2.0',
    'weights_uri','timesfm_2p5_200m.onnx',
    'io_spec', json_object(
      'layout','sequence','input','context',
      'outputs', json_object('point','point_fan','quantile','quant_fan'),
      'quantiles', json_array(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9),
      'patch', 512, 'fixed_context', json('true'),
      'flip_invariance', json('true'), 'continuous_head', json('true'),
      'quantile_crossing_repair', json('true'), 'denormalize','instance')));

TimesFM weights are Apache-2.0; the exported graph is a large derivative kept
out of git and regenerated by this script.

Run: uv run --with "setuptools<81" --with "timesfm[torch]" --with torch \
       --with onnx --with onnxscript --with onnxruntime --with numpy \
       python scripts/export_timesfm_onnx.py [OUT.onnx]
"""
import sys
import numpy as np
import torch
import torch.nn as nn
import timesfm

CTX, H = 512, 64
QUANTILES = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
# Full config: we compile with flip-invariance + continuous head ON so the
# reference forecast() we validate against is the real model, but we only export
# a single decode and rebuild those two steps in reconstruct()/the C server.
CFG = dict(max_context=CTX, max_horizon=H, normalize_inputs=True,
           use_continuous_quantile_head=True, force_flip_invariance=True,
           fix_quantile_crossing=True, infer_is_positive=False)


class TimesFMCore(nn.Module):
    """The exportable core: normalize -> one decode -> raw (point, quantile) fans.

    No flip-invariance (second decode), no continuous head (in-place mutation),
    no crossing repair, no denorm. Those are reconstructed outside the graph."""

    def __init__(self, wrapped):
        super().__init__()
        self.mdl = wrapped.model

    def forward(self, context):  # context [1, 512]
        masks = torch.zeros_like(context, dtype=torch.bool)
        mu = context.mean(-1, keepdim=True)
        sigma = context.std(-1, keepdim=True)
        x = (context - mu) / torch.where(sigma < 1e-6, torch.ones_like(sigma), sigma)
        pf, qs, _ = self.mdl.decode(H, x, masks)
        point_fan = pf[:, -1, :H, :]  # [1, H, 10] normalized
        quant_fan = qs[:, :H, :]      # [1, H, 10] normalized
        return point_fan, quant_fan


def _flipq(t):  # keep col 0 (mean), reverse deciles 1..9  -> numpy [., ., 10]
    return np.concatenate([t[..., :1], t[..., 1:][..., ::-1]], axis=-1)


def reconstruct(sess, context):
    """Rebuild the full TimesFM fan from the two-output core: flip-invariance +
    continuous head + crossing repair + denorm. `context` is raw [1, 512]."""
    c = context.astype(np.float32)
    mu = c.mean(-1, keepdims=True)
    sigma = c.std(-1, keepdims=True)
    sigma = np.where(sigma < 1e-6, 1.0, sigma)
    refl = (2 * mu - c).astype(np.float32)  # normalizes to -x internally

    a1, b1 = sess.run(None, {"context": c})           # point, quantile (normalized)
    a2, b2 = sess.run(None, {"context": refl})
    ff = (a1 - _flipq(a2)) / 2                          # [1, H, 10]
    qs = (b1 - _flipq(b2)) / 2
    out = ff.copy()
    for qi in (1, 2, 3, 4, 6, 7, 8, 9):                # continuous quantile head
        out[..., qi] = qs[..., qi] - qs[..., 5] + ff[..., 5]
    for i in (4, 3, 2, 1):                             # crossing repair
        out[..., i] = np.minimum(out[..., i], out[..., i + 1])
    for i in (6, 7, 8, 9):
        out[..., i] = np.maximum(out[..., i], out[..., i - 1])
    out = out * sigma[..., None] + mu[..., None]       # denorm
    return out[..., 1:10].transpose(0, 2, 1)           # deciles -> [1, 9, H]


def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else "timesfm_2p5_200m.onnx"
    M = timesfm.TimesFM_2p5_200M_torch
    wrapped = M.from_pretrained(M.DEFAULT_REPO_ID)
    wrapped.compile(timesfm.ForecastConfig(**CFG))
    net = TimesFMCore(wrapped).eval()

    sample = torch.randn(1, CTX) * 10 + 50
    torch.onnx.export(net, (sample,), out_path, input_names=["context"],
                      output_names=["point_fan", "quant_fan"], dynamo=True,
                      opset_version=18)
    print(f"exported {out_path}")

    import onnxruntime as ort
    sess = ort.InferenceSession(out_path, providers=["CPUExecutionProvider"])
    worst = 0.0
    for _ in range(4):
        c = (torch.randn(1, CTX) * 7 + 30).numpy()
        got = reconstruct(sess, c)                     # [1, 9, H] full reconstruction
        _, q = wrapped.forecast(H, [c[0]])             # the real full pipeline
        ref = np.asarray(q)[0][:, 1:10].T[None]        # [1, 9, H]
        worst = max(worst, float(np.abs(ref - got).max()))
    print(f"reconstruction vs full TimesFM pipeline: max abs diff {worst:.2e} "
          f"({'OK' if worst < 1e-2 else 'FAIL'})")
    if worst >= 1e-2:
        sys.exit(1)


if __name__ == "__main__":
    main()
